name: soz_ucar
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  build_runner: null
  cloud_firestore: ^4.4.2
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  firebase_core: ^2.11.0
  firebase_database: ^10.0.13
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+5
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.4.0
  google_mobile_ads: ^3.0.0
  lottie: null
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0
  provider: ^6.0.5
  share_plus: ^7.0.2
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/lottie/