// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp3VK6rN2-YnTDFI1OOlPRhRDGbBFn9I0',
    appId: '1:732578990297:web:1c5c25a1d60193192096c8',
    messagingSenderId: '732578990297',
    projectId: 'ozlusozler-13ec6',
    authDomain: 'ozlusozler-13ec6.firebaseapp.com',
    databaseURL: 'https://ozlusozler-13ec6-default-rtdb.firebaseio.com',
    storageBucket: 'ozlusozler-13ec6.appspot.com',
    measurementId: 'G-E7QXQK2FXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgzoUl-7rnqE6F327WYlziEgsx1RvCUCY',
    appId: '1:732578990297:android:8983bedf98f1a2742096c8',
    messagingSenderId: '732578990297',
    projectId: 'ozlusozler-13ec6',
    databaseURL: 'https://ozlusozler-13ec6-default-rtdb.firebaseio.com',
    storageBucket: 'ozlusozler-13ec6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd-9r3-576VVyjziBmtsxwmtfyJ32XddI',
    appId: '1:732578990297:ios:fefd72761df9763e2096c8',
    messagingSenderId: '732578990297',
    projectId: 'ozlusozler-13ec6',
    databaseURL: 'https://ozlusozler-13ec6-default-rtdb.firebaseio.com',
    storageBucket: 'ozlusozler-13ec6.appspot.com',
    iosClientId: '732578990297-q914i9596odu16rp5qi88i8hodv6sqa5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ozluSozlerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd-9r3-576VVyjziBmtsxwmtfyJ32XddI',
    appId: '1:732578990297:ios:fefd72761df9763e2096c8',
    messagingSenderId: '732578990297',
    projectId: 'ozlusozler-13ec6',
    databaseURL: 'https://ozlusozler-13ec6-default-rtdb.firebaseio.com',
    storageBucket: 'ozlusozler-13ec6.appspot.com',
    iosClientId: '732578990297-q914i9596odu16rp5qi88i8hodv6sqa5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ozluSozlerFlutter',
  );
}
